### ISSUE TITLE
Missing functions in File and Dir

### ISSUE THREAD

**Issue by peterlerche** [AliBasicCoder/fs-pro#139]
Hi,

It looks like "File exits(): any" is not compiled into build 3.11.0. 

```Typescript
  import pkg from 'fs-pro';
    const { File } = pkg;
    const file = new File('/my/dir/','myfile.txt');
    if(file.exits()){
        // file.exist() function does not exist. 
    }
```

By the way!  "exits" is spelled incorrectly. It should be "exist"

I have the same issue with "Dir CreateFile()"

**Comment by AliBasicCoder** [comment]
Could I see the full error message

**Comment by peterlerche** [comment]
Maybe I jumped the gun! 
  I can see that it occurs only when I run the code within a Svelte component. 
It looks like it is a hydration issue. I will look further into the issue.

<script lang="ts">   

  import pkg from 'fs-pro';   
    const { File } = pkg;   
    const file = new File('/my/dir/','myfile.txt');   
    if(file.exits()){   
        // file.exist() function does not exist.    
    }   

</script>   

Question: Will we see fs-pro as an esm module?

**Comment by AliBasicCoder** [comment]
> Maybe I jumped the gun! 
>   I can see that it occurs only when I run the code within a Svelte component. 
> It looks like it is a hydration issue. I will look further into the issue.
> 
> <script lang="ts">
> ```typescript
>   import pkg from 'fs-pro';
>     const { File } = pkg;
>     const file = new File('/my/dir/','myfile.txt');
>     if(file.exits()){
>         // file.exist() function does not exist. 
>     }
> ```
> </script>
> 
> Question: Will we see fs-pro as an esm module?

I'm gonna see if it's possible and if it is, then yes

**Comment by AliBasicCoder** [comment]
> Maybe I jumped the gun! 
>   I can see that it occurs only when I run the code within a Svelte component. 
> It looks like it is a hydration issue. I will look further into the issue.
> 
> <script lang="ts">
> ```typescript
>   import pkg from 'fs-pro';
>     const { File } = pkg;
>     const file = new File('/my/dir/','myfile.txt');
>     if(file.exits()){
>         // file.exist() function does not exist. 
>     }
> ```
> </script>
> 
> Question: Will we see fs-pro as an esm module?

Are you sure this script has access to fs and other node built-in modules?

**Comment by AliBasicCoder** [comment]
i deprecated File.exits and Dir.exits and added File.exists and Dir.exists in v3.12.0 commit [5b4e183](https://github.com/AliBasicCoder/fs-pro/commit/5b4e183a04f24027d3fbc6cdc51826c53bf32dde)

**Comment by AliBasicCoder** [comment]
i guess making fs-pro into an esm is hard if it's even possible

**Comment by AliBasicCoder** [comment]
@peterlerche hi, since you're the only one who made an issue about the package, do think this package is worth making the effort into trying to make alive again or should i let it die?

i was kinda busy for the last 2 years i just got back doing open source

**Comment by peterlerche** [comment]
@AliBasicCoder Sorry for not getting back to you sooner, but I have moved on from the NPM ecosystem. However, much has happened over the last two years, so I am not sure that your effort would materialize in more users of your package. Just my two cents.
